# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: abdoufermat5.Herbarium
PackageVersion: 0.2.0
InstallerLocale: en-US
UpgradeBehavior: install
Commands:
- herbarium
Protocols:
- herbarium-app
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/abdoufermat5/herbarium/releases/download/v0.2.0/herbarium_0.2.0_x64-setup.exe
  InstallerSha256: 9F4F1FE3643E4017B5519EE03CAC31FCBAED04A0899BE1019B0C1A4FAFB3EB0F
  ProductCode: herbarium
  AppsAndFeaturesEntries:
  - DisplayName: herbarium
    Publisher: herbarium
    ProductCode: herbarium
  InstallationMetadata:
    DefaultInstallLocation: '%LocalAppData%\herbarium'
- Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://github.com/abdoufermat5/herbarium/releases/download/v0.2.0/herbarium_0.2.0_x64_en-US.msi
  InstallerSha256: 5739D289BBC3CC2B147559D14036E86D3ED8866C28B78DB14302984732547307
  ProductCode: '{64E24668-EF26-4583-9FAF-CB9093D431B1}'
  AppsAndFeaturesEntries:
  - DisplayName: herbarium
    Publisher: herbarium
    ProductCode: '{64E24668-EF26-4583-9FAF-CB9093D431B1}'
    UpgradeCode: '{1F96223B-0342-54E5-9875-57A2926E3197}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%/herbarium'
ManifestType: installer
ManifestVersion: 1.12.0
